Vagrant.configure("2") do |config|
  config.vm.define :node1 do |config|
    #config.vm.boot_mode = "gui"
    config.vm.hostname  = "node1.example.org"
    config.vm.box       = "ganeti-centos-6-20130411"
    config.vm.box_url   = "http://ftp.osuosl.org/pub/osl/ganeti-tutorial/ganeti-centos-6-20130411.box"
    config.vm.synced_folder "../", "/vagrant", :owner => "vagrant", :group => "vagrant"
    config.vm.network :private_network, ip: "33.33.33.11", adapter: 2, auto_config: "false"
    config.vm.network :private_network, ip: "33.33.34.11", adapter: 3, auto_config: "false"
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 768]
      # uncomment to disable hardware virt
      #vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
    end
    config.vm.provision :puppet do |puppet|
      puppet.manifests_path   = "../modules/ganeti_tutorial/nodes"
      puppet.module_path      = "../modules"
      puppet.manifest_file    = "node1.pp"
    end
  end

  config.vm.define :node2 do |config|
    #config.vm.boot_mode = "gui"
    config.vm.hostname  = "node2.example.org"
    config.vm.box       = "ganeti-centos-6-20130411"
    config.vm.box_url   = "http://ftp.osuosl.org/pub/osl/ganeti-tutorial/ganeti-centos-6-20130411.box"
    config.vm.share_folder "v-root", "/vagrant", "../", :owner => "vagrant", :group => "vagrant"
    config.vm.network :private_network, ip: "33.33.33.12", adapter: 2, auto_config: "false"
    config.vm.network :private_network, ip: "33.33.34.12", adapter: 3, auto_config: "false"
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 768]
      # uncomment to disable hardware virt
      #vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
    end
    config.vm.provision :puppet do |puppet|
      puppet.manifests_path   = "../modules/ganeti_tutorial/nodes"
      puppet.module_path      = "../modules"
      puppet.manifest_file    = "node2.pp"
    end
  end

  config.vm.define :node3 do |config|
    #config.vm.boot_mode = "gui"
    config.vm.hostname  = "node3.example.org"
    config.vm.box       = "ganeti-centos-6-20130411"
    config.vm.box_url   = "http://ftp.osuosl.org/pub/osl/ganeti-tutorial/ganeti-centos-6-20130411.box"
    config.vm.share_folder "v-root", "/vagrant", "../", :owner => "vagrant", :group => "vagrant"
    config.vm.network :private_network, ip: "33.33.33.13", adapter: 2, auto_config: "false"
    config.vm.network :private_network, ip: "33.33.34.13", adapter: 3, auto_config: "false"
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 768]
      # uncomment to disable hardware virt
      #vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
    end
    config.vm.provision :puppet do |puppet|
      puppet.manifests_path   = "../modules/ganeti_tutorial/nodes"
      puppet.module_path      = "../modules"
      puppet.manifest_file    = "node3.pp"
    end
  end
end
